version: "1"
services:
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /home/ubuntu/ssl:/etc/nginx/certs

  server:
    container_name: flask_server
    build: ./server
    expose:
      - 5000
    volumns:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
