version: "1"
services:
  frontend:
    container_name: frontend
    build:
      - context: ./src
      - dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs

  backend:
    restart: always
    container_name: backend
    build:
      - context: ./server
      - dockerfile: Dockerfile
    expose:
      - 5000
    volumns:
      - ./server:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
